const products = [
  // 🧥 CLOTH
  {
    id: 1,
    category: "Cloth",
    title: "Men's Classic Denim Jacket",
    price: 39.99,
    oldPrice: 49.99,
    image: "/images/Cloth/Men's Classic Denim Jacket.jpg",
    description: "Stylish men's denim jacket made from high-quality cotton blend. Perfect for casual wear and layering during cool seasons. Features classic button closure, chest pockets, and durable stitching. Comfortable, versatile, and never goes out of fashion. Ideal for streetwear lovers and trendsetters alike.",
    sold: 124,
    rating: 4.7,
    quntity: 15,
    about: "A timeless denim jacket designed for comfort and style. Made with premium materials to ensure long-lasting wear. Pair it with jeans or chinos for an effortlessly cool look every day.",
    size: "large",
    color: ["Blue", "Black"],
  },
  {
    id: 2,
    category: "Cloth",
    title: "Casual Cotton T-Shirt",
    price: 15.00,
    oldPrice: 19.00,
    image: "/images/Cloth/Casual Cotton T-Shirt.webp",
    description: "Soft cotton T-shirt offering maximum comfort and breathability. Minimalist design perfect for everyday wear and layering. Machine washable and durable.",
    sold: 210,
    rating: 4.8,
    quntity: 40,
    about: "A must-have casual tee that fits any outfit. Lightweight, comfortable, and available in classic colors for all-day wear.",
    size: "medium",
    color: ["White", "Gray", "Black"],
  },
  {
    id: 3,
    category: "Cloth",
    title: "Slim Fit Jeans",
    price: 42.00,
    oldPrice: 52.00,
    image: "/images/Cloth/Slim Fit Jeans.webp",
    description: "High-quality slim-fit jeans crafted from stretchable denim fabric. Modern look with 5-pocket design and sturdy zipper closure.",
    sold: 176,
    rating: 4.6,
    quntity: 20,
    about: "Stay stylish and comfortable with these premium slim-fit jeans. Perfect for casual and semi-formal outfits.",
    size: "large",
    color: ["Blue", "Dark Blue"],
  },
  {
    id: 4,
    category: "Cloth",
    title: "Women's Summer Dress",
    price: 34.99,
    oldPrice: 44.99,
    image: "/images/Cloth/Women's Summer Dress.jpg",
    description: "Lightweight floral summer dress with adjustable straps. Breathable fabric ideal for hot weather and casual outings.",
    sold: 98,
    rating: 4.7,
    quntity: 18,
    about: "Embrace summer vibes with this elegant floral dress. Stylish, comfortable, and perfect for any sunny day.",
    size: "medium",
    color: ["Red", "Yellow"],
  },
  {
    id: 5,
    category: "Cloth",
    title: "Men's Hoodie Classic Fit",
    price: 29.99,
    oldPrice: 39.99,
    image: "/images/Cloth/Men's Hoodie Classic Fit.jpg",
    description: "Comfortable fleece hoodie designed for warmth and style. Features adjustable drawstring and kangaroo pocket.",
    sold: 165,
    rating: 4.8,
    quntity: 25,
    about: "A cozy hoodie made for everyday comfort. Ideal for workouts, casual wear, and cool weather.",
    size: "large",
    color: ["Black", "Gray"],
  },

  // 💍 JEWELRY
  {
    id: 6,
    category: "Jewelry",
    title: "Elegant Silver Necklace",
    price: 59.00,
    oldPrice: 75.00,
    image: "/images/Jewelry/Elegant Silver Necklace.webp",
    description: "Elegant sterling silver necklace with minimalist pendant design. Polished finish adds a subtle shine suitable for any outfit.",
    sold: 98,
    rating: 4.8,
    quntity: 12,
    about: "Add sophistication to your style with this elegant silver necklace. Complements both formal and casual looks.",
    size: "medium",
    color: ["Silver"],
  },
  {
    id: 7,
    category: "Jewelry",
    title: "Gold Hoop Earrings",
    price: 49.00,
    oldPrice: 59.00,
    image: "/images/Jewelry/Gold Hoop Earrings.jpg",
    description: "Classic 18K gold-plated hoop earrings with secure latch closure. Lightweight and hypoallergenic for all-day comfort.",
    sold: 132,
    rating: 4.7,
    quntity: 20,
    about: "Timeless elegance in a simple design. Perfect for adding a touch of luxury to your daily wear.",
    size: "small",
    color: ["Gold"],
  },
  {
    id: 8,
    category: "Jewelry",
    title: "Diamond Engagement Ring",
    price: 299.00,
    oldPrice: 359.00,
    image: "/images/Jewelry/Diamond Engagement Ring.jpg",
    description: "Stunning engagement ring featuring a high-quality cubic zirconia stone. Sparkles brilliantly like a real diamond.",
    sold: 54,
    rating: 4.9,
    quntity: 5,
    about: "Celebrate love with this elegant and timeless diamond-style ring. Designed to impress and last a lifetime.",
    size: "small",
    color: ["Silver"],
  },
  {
    id: 9,
    category: "Jewelry",
    title: "Leather Bracelet Set",
    price: 25.00,
    oldPrice: 32.00,
    image: "/images/Jewelry/Leather Bracelet Set.webp",
    description: "Set of three adjustable leather bracelets with metal accents. Perfect for casual wear and gifting.",
    sold: 176,
    rating: 4.5,
    quntity: 30,
    about: "Add an edgy touch to your style with these versatile leather bracelets. Comfortable and stylish for everyday wear.",
    size: "medium",
    color: ["Brown", "Black"],
  },
  {
    id: 10,
    category: "Jewelry",
    title: "Pearl Drop Earrings",
    price: 39.00,
    oldPrice: 49.00,
    image: "/images/Jewelry/Pearl Drop Earrings.webp",
    description: "Elegant pearl earrings with gold-tone base. Perfect accessory for formal events or everyday elegance.",
    sold: 67,
    rating: 4.8,
    quntity: 15,
    about: "Refined and classic — these pearl earrings bring timeless grace to any outfit.",
    size: "small",
    color: ["White", "Gold"],
  },

  // 📱 ELECTRONICS
  {
    id: 11,
    category: "Electronics",
    title: "Wireless Bluetooth Earbuds",
    price: 69.00,
    oldPrice: 89.00,
    image: "/images/Electronics/Wireless Bluetooth Earbuds.jpg",
    description: "High-quality wireless earbuds with noise-cancelling technology. Deliver clear sound and deep bass for immersive listening.",
    sold: 312,
    rating: 4.6,
    quntity: 25,
    about: "Experience freedom and clarity with our wireless Bluetooth earbuds. Seamless connectivity and powerful audio.",
    size: "small",
    color: ["White", "Black"],
  },
  {
    id: 12,
    category: "Electronics",
    title: "Smartphone X9 Pro",
    price: 599.00,
    oldPrice: 699.00,
    image: "/images/Electronics/Smartphone X9 Pro.jpeg",
    description: "Flagship smartphone with AMOLED display, 128GB storage, and 50MP camera. Sleek design and fast performance.",
    sold: 425,
    rating: 4.7,
    quntity: 15,
    about: "Power meets style in this high-performance smartphone. Capture every moment with stunning clarity.",
    size: "medium",
    color: ["Black", "Blue"],
  },
  {
    id: 13,
    category: "Electronics",
    title: "Smart Watch FitBand 2",
    price: 79.00,
    oldPrice: 99.00,
    image: "/images/Electronics/Smart Watch FitBand 2.webp" ,
    description: "Fitness smartwatch with step, heart rate, and sleep tracking. Long battery life and water resistance.",
    sold: 276,
    rating: 4.8,
    quntity: 22,
    about: "Track your health and fitness with precision using FitBand 2. Lightweight, stylish, and reliable.",
    size: "medium",
    color: ["Black", "Pink"],
  },
  {
    id: 14,
    category: "Electronics",
    title: "Gaming Headset X5",
    price: 59.00,
    oldPrice: 79.00,
    image: "/images/Electronics/Gaming Headset X5.avif",
    description: "Immersive over-ear gaming headset with noise isolation and RGB lighting. Compatible with PC and consoles.",
    sold: 154,
    rating: 4.6,
    quntity: 20,
    about: "Take your gaming to the next level with crystal-clear sound and comfort. Designed for long gaming sessions.",
    size: "large",
    color: ["Black", "Red"],
  },
  {
    id: 15,
    category: "Electronics",
    title: "Portable Bluetooth Speaker",
    price: 45.00,
    oldPrice: 55.00,
    image: "/images/Electronics/Portable Bluetooth Speaker.jpg",
    description: "Compact wireless speaker with deep bass and clear sound. 10-hour battery life and water-resistant build.",
    sold: 218,
    rating: 4.7,
    quntity: 30,
    about: "Enjoy your music anywhere with this portable and powerful speaker. Perfect for travel and outdoor use.",
    size: "medium",
    color: ["Blue", "Black"],
  },

  // 👟 SHOES
  {
    id: 16,
    category: "Shoes",
    title: "Running Sneakers Pro X1",
    price: 79.99,
    oldPrice: 99.99,
    image: "/images/Shoes/Running Sneakers Pro X1.webp",
    description: "Lightweight running shoes designed for comfort and performance. Breathable mesh upper keeps your feet cool and dry.",
    sold: 157,
    rating: 4.5,
    quntity: 20,
    about: "Run faster and longer with our Pro X1 sneakers. Engineered for comfort, flexibility, and support.",
    size: "medium",
    color: ["Gray", "Blue", "Black"],
  },
  {
    id: 17,
    category: "Shoes",
    title: "Women's Casual Sneakers",
    price: 59.00,
    oldPrice: 75.00,
    image: "/images/Shoes/Women's Casual Sneakers.webp",
    description: "Trendy sneakers with cushioned soles and breathable material. Perfect for everyday walking and outings.",
    sold: 188,
    rating: 4.6,
    quntity: 22,
    about: "Step out in style with these comfy and modern sneakers. Ideal for both casual and sporty looks.",
    size: "medium",
    color: ["White", "Pink"],
  },
  {
    id: 18,
    category: "Shoes",
    title: "Leather Formal Shoes",
    price: 89.00,
    oldPrice: 109.00,
    image: "/images/Shoes/Leather Formal Shoes.webp",
    description: "Premium leather formal shoes with non-slip sole. Ideal for business meetings and special occasions.",
    sold: 73,
    rating: 4.8,
    quntity: 12,
    about: "Add class and elegance to your formal look. Crafted from genuine leather for superior comfort.",
    size: "large",
    color: ["Brown", "Black"],
  },
  {
    id: 19,
    category: "Shoes",
    title: "Sports Training Shoes",
    price: 69.00,
    oldPrice: 89.00,
    image: "/images/Shoes/Sports Training Shoes.webp",
    description: "Durable sports shoes with flexible sole and cushioned insole. Built for gym, running, and outdoor training.",
    sold: 120,
    rating: 4.7,
    quntity: 18,
    about: "Train harder and move freely with these high-performance training shoes.",
    size: "medium",
    color: ["Black", "Orange"],
  },
  {
    id: 20,
    category: "Shoes",
    title: "Classic Canvas Sneakers",
    price: 39.00,
    oldPrice: 49.00,
    image: "/images/Shoes/Classic Canvas Sneakers.webp",
    description: "Timeless canvas sneakers with rubber soles. Lightweight, durable, and easy to match with any outfit.",
    sold: 204,
    rating: 4.8,
    quntity: 25,
    about: "A classic staple that never goes out of style. Perfect for casual wear and everyday comfort.",
    size: "medium",
    color: ["White", "Navy"],
  },
  // 👜 Bags & Accessories
{
  id: 101,
  category: "Bags & Accessories",
  title: "Leather Crossbody Bag",
  price: 59.00,
  oldPrice: 75.00,
  image: "/images/Bags & Accessories/Leather Crossbody Bag.webp",
  description: "Elegant leather crossbody bag with adjustable strap and multiple compartments. Perfect for travel or daily use. Compact yet spacious design keeps essentials organized with ease.",
  sold: 142,
  rating: 4.8,
  quntity: 15,
  about: "Experience the perfect balance between fashion and functionality. This leather crossbody bag is crafted with premium materials, offering timeless elegance and durability. Designed for modern lifestyles, it features soft lining, sturdy zippers, and an adjustable strap that ensures comfort all day long.",
  size: "medium",
  color: ["Brown", "Black"],
},
{
  id: 102,
  category: "Bags & Accessories",
  title: "Men’s Classic Wallet",
  price: 35.00,
  oldPrice: 45.00,
  image: "/images/Bags & Accessories/Men’s Classic Wallet.jpg",
  description: "Slim leather wallet with multiple card slots and a smooth finish. Durable and stylish, perfect for everyday use and gifting.",
  sold: 210,
  rating: 4.6,
  quntity: 25,
  about: "Keep your essentials neatly organized in this classic men's wallet. Made from genuine leather with a soft-touch finish, it provides durability and a luxurious feel. The minimalist design easily fits into pockets while offering maximum space for your cards, cash, and ID.",
  size: "small",
  color: ["Black", "Dark Brown"],
},
{
  id: 103,
  category: "Bags & Accessories",
  title: "Travel Backpack 35L",
  price: 69.00,
  oldPrice: 89.00,
  image: "/images/Bags & Accessories/Travel Backpack 35L.jpg",
  description: "Durable travel backpack with 35L capacity, water-resistant fabric, and ergonomic padding for comfort. Great for work, travel, or hiking.",
  sold: 188,
  rating: 4.7,
  quntity: 30,
  about: "Travel smarter with this 35L backpack designed for comfort and durability. It includes padded straps, multiple compartments, and a laptop sleeve. Made with waterproof materials to keep your belongings safe wherever you go, whether it’s daily commuting or weekend adventures.",
  size: "large",
  color: ["Gray", "Navy Blue"],
},
{
  id: 104,
  category: "Bags & Accessories",
  title: "Stylish Sunglasses",
  price: 25.00,
  oldPrice: 35.00,
  image: "/images/Bags & Accessories/Stylish Sunglasses.webp",
  description: "Trendy sunglasses with UV400 protection. Lightweight and durable frame suitable for all face shapes. Ideal for daily wear and travel.",
  sold: 92,
  rating: 4.5,
  quntity: 20,
  about: "Protect your eyes with confidence and style. These sunglasses feature UV400 lenses that block harmful rays, ensuring comfort and clear vision. Perfect for fashion lovers who want both functionality and flair.",
  size: "medium",
  color: ["Black", "Gold"],
},
{
  id: 105,
  category: "Bags & Accessories",
  title: "Smart Watch Strap Set",
  price: 19.99,
  oldPrice: 29.99,
  image: "/images/Bags & Accessories/Smart Watch Strap Set.jpg",
  description: "Set of premium silicone straps compatible with most smartwatches. Breathable, flexible, and ideal for sports or daily wear.",
  sold: 77,
  rating: 4.6,
  quntity: 28,
  about: "Upgrade your smartwatch style with these premium replacement straps. Made from soft silicone, they provide comfort for all-day wear. Available in multiple colors, designed to fit securely and withstand active lifestyles.",
  size: "medium",
  color: ["Black", "White", "Red"],
},

// 🍳 Home & Kitchen
{
  id: 201,
  category: "Home & Kitchen",
  title: "Electric Kettle 1.8L",
  price: 29.00,
  oldPrice: 39.00,
  image: "/images/Home & Kitchen/Electric Kettle 1.8L.webp",
  description: "Fast-boil electric kettle with 1.8L capacity and auto shut-off feature. Durable stainless steel body ensures long-lasting use.",
  sold: 320,
  rating: 4.7,
  quntity: 35,
  about: "Boil water quickly and safely with this 1.8L electric kettle. Designed with advanced safety features like automatic shut-off and boil-dry protection. The sleek stainless steel design fits perfectly in any modern kitchen.",
  size: "medium",
  color: ["Silver", "Black"],
},
{
  id: 202,
  category: "Home & Kitchen",
  title: "Ceramic Dinner Set (12 pcs)",
  price: 75.00,
  oldPrice: 89.00,
  image: "/images/Home & Kitchen/Ceramic Dinner Set (12 pcs).webp",
  description: "Elegant ceramic dinnerware set includes plates, bowls, and mugs. Microwave and dishwasher safe, perfect for daily dining.",
  sold: 146,
  rating: 4.8,
  quntity: 20,
  about: "Upgrade your dining experience with this beautifully designed 12-piece ceramic dinner set. Each piece is crafted to perfection, combining strength, elegance, and ease of cleaning. Perfect for family meals or special occasions.",
  size: "large",
  color: ["White", "Cream"],
},
{
  id: 203,
  category: "Home & Kitchen",
  title: "Stainless Steel Cookware Set",
  price: 99.00,
  oldPrice: 119.00,
  image: "/images/Home & Kitchen/Stainless Steel Cookware Set.avif",
  description: "Complete cookware set with non-stick coating. Includes pots, pans, and lids. Durable and heat-resistant for all stovetops.",
  sold: 208,
  rating: 4.6,
  quntity: 18,
  about: "Cook like a professional with this stainless steel cookware set. Designed for maximum durability and even heat distribution. Whether you’re simmering sauces or frying vegetables, this set delivers reliable results every time.",
  size: "large",
  color: ["Silver"],
},
{
  id: 204,
  category: "Home & Kitchen",
  title: "Air Fryer 5L",
  price: 89.00,
  oldPrice: 110.00,
  image: "/images/Home & Kitchen/Air Fryer 5L.jpg",
  description: "Healthy air fryer with 5L capacity and digital controls. Enjoy crispy results using up to 85% less oil. Easy to clean and safe to use.",
  sold: 270,
  rating: 4.9,
  quntity: 25,
  about: "Enjoy delicious meals with less oil using this powerful 5L air fryer. Featuring digital temperature control, timer, and removable non-stick basket, it makes healthy cooking faster and easier than ever.",
  size: "medium",
  color: ["Black", "White"],
},
{
  id: 205,
  category: "Home & Kitchen",
  title: "Smart LED Lamp",
  price: 35.00,
  oldPrice: 45.00,
  image: "/images/Home & Kitchen/Smart LED Lamp.png",
  description: "Modern smart LED lamp with adjustable brightness and color modes. Controlled via app or touch panel. Energy-efficient and elegant.",
  sold: 115,
  rating: 4.7,
  quntity: 22,
  about: "Light up your home with innovation. The Smart LED Lamp offers adjustable color temperatures, remote app control, and voice compatibility with Alexa and Google Home. Perfect for bedrooms, offices, or cozy reading corners.",
  size: "medium",
  color: ["White", "Silver"],
},

// 💄 Beauty & Cosmetics
{
  id: 301,
  category: "Beauty & Cosmetics",
  title: "Matte Liquid Lipstick Set",
  price: 25.00,
  oldPrice: 35.00,
  image: "/images/Beauty & Cosmetics/Matte Liquid Lipstick Set.webp",
  description: "Long-lasting matte liquid lipstick with rich pigmentation. Non-drying formula for smooth and comfortable wear all day.",
  sold: 210,
  rating: 4.8,
  quntity: 40,
  about: "Get bold, beautiful lips with our Matte Liquid Lipstick Set. The creamy texture glides effortlessly and sets into a smooth matte finish. Available in multiple shades, each designed to enhance your natural beauty and confidence.",
  size: "small",
  color: ["Red", "Nude", "Pink"],
},
{
  id: 302,
  category: "Beauty & Cosmetics",
  title: "Hydrating Face Serum",
  price: 39.00,
  oldPrice: 49.00,
  image: "/images/Beauty & Cosmetics/Hydrating Face Serum.webp",
  description: "Deep-hydrating serum enriched with hyaluronic acid and vitamin C. Brightens and revitalizes dull, tired skin for a radiant look.",
  sold: 182,
  rating: 4.9,
  quntity: 28,
  about: "Revitalize your skin with this luxurious hydrating serum. Infused with powerful antioxidants and nutrients, it restores moisture balance and boosts elasticity. Perfect for all skin types, leaving your complexion smoother and more luminous.",
  size: "small",
  color: ["Transparent"],
},
{
  id: 303,
  category: "Beauty & Cosmetics",
  title: "Compact Foundation Powder",
  price: 32.00,
  oldPrice: 42.00,
  image: "/images/Beauty & Cosmetics/Compact Foundation Powder.jpg",
  description: "Lightweight foundation powder provides flawless coverage with a natural matte finish. Suitable for all skin tones.",
  sold: 130,
  rating: 4.6,
  quntity: 35,
  about: "Achieve a flawless complexion with this silky foundation powder. Its lightweight formula blends easily, controlling shine and smoothing out imperfections while allowing your skin to breathe naturally.",
  size: "medium",
  color: ["Beige", "Ivory"],
},
{
  id: 304,
  category: "Beauty & Cosmetics",
  title: "Volumizing Mascara",
  price: 19.00,
  oldPrice: 25.00,
  image: "/images/Beauty & Cosmetics/Volumizing Mascara.webp",
  description: "Waterproof volumizing mascara with intense black pigment. Lifts and defines lashes for a dramatic, long-lasting look.",
  sold: 174,
  rating: 4.7,
  quntity: 30,
  about: "Transform your lashes with instant volume and definition. This mascara’s advanced formula adds body without clumps and resists smudging, keeping your eyes looking captivating all day.",
  size: "small",
  color: ["Black"],
},
{
  id: 305,
  category: "Beauty & Cosmetics",
  title: "Aloe Vera Moisturizing Cream",
  price: 22.00,
  oldPrice: 30.00,
  image: "/images/Beauty & Cosmetics/Aloe Vera Moisturizing Cream.jpg",
  description: "Natural aloe vera cream deeply moisturizes and soothes the skin. Gentle, fast-absorbing, and suitable for daily use.",
  sold: 196,
  rating: 4.8,
  quntity: 40,
  about: "Enjoy soft, refreshed skin with this aloe-based moisturizing cream. It nourishes, hydrates, and soothes irritation while protecting against dryness. Ideal for sensitive and normal skin alike, leaving a lasting glow.",
  size: "medium",
  color: ["Green", "White"],
},
// 🏃 Sports & Outdoors
{
  id: 401,
  category: "Sports & Outdoors",
  title: "Mountain Bike Pro 26”",
  price: 299.00,
  oldPrice: 349.00,
  image: "/images/Sports & Outdoors/Mountain Bike Pro 26.jpg",
  description: "Durable 26-inch mountain bike with alloy frame and shock-absorbing suspension. Ideal for trails, hills, and daily commuting.",
  sold: 112,
  rating: 4.7,
  quntity: 10,
  about: "Conquer every terrain with this professional-grade mountain bike. Its lightweight yet sturdy frame ensures durability, while advanced suspension absorbs impact for a smooth ride. Perfect for outdoor enthusiasts who crave adventure and performance.",
  size: "large",
  color: ["Red", "Black"],
},
{
  id: 402,
  category: "Sports & Outdoors",
  title: "Yoga Mat Pro Grip",
  price: 35.00,
  oldPrice: 45.00,
  image: "/images/Sports & Outdoors/Yoga Mat Pro Grip.jpg",
  description: "Eco-friendly yoga mat with anti-slip surface and thick cushioning. Provides stability and comfort for all yoga levels.",
  sold: 168,
  rating: 4.8,
  quntity: 20,
  about: "Enhance your yoga practice with this premium mat that combines comfort, grip, and durability. Made from non-toxic, eco-safe materials, it offers excellent support and balance for all poses.",
  size: "medium",
  color: ["Purple", "Blue", "Green"],
},
{
  id: 403,
  category: "Sports & Outdoors",
  title: "Adjustable Dumbbell Set 20kg",
  price: 89.00,
  oldPrice: 109.00,
  image: "/images/Sports & Outdoors/Adjustable Dumbbell Set 20kg.jpg",
  description: "Adjustable dumbbell set up to 20kg with non-slip handles. Perfect for home workouts and strength training.",
  sold: 132,
  rating: 4.7,
  quntity: 18,
  about: "Transform your home into a personal gym with this compact dumbbell set. Easily adjustable for various exercises, helping you build muscle and stay fit without bulky equipment.",
  size: "medium",
  color: ["Black"],
},
{
  id: 404,
  category: "Sports & Outdoors",
  title: "Waterproof Sports Watch",
  price: 49.00,
  oldPrice: 65.00,
  image: "/images/Sports & Outdoors/Waterproof Sports Watch.jpg",
  description: "Rugged waterproof sports watch with stopwatch and heart-rate tracker. Built for endurance and outdoor activity.",
  sold: 94,
  rating: 4.6,
  quntity: 22,
  about: "Stay active and on time with this multifunctional sports watch. Designed for outdoor enthusiasts, it combines durability, waterproofing, and smart tracking to support your fitness goals.",
  size: "medium",
  color: ["Black", "Blue"],
},
{
  id: 405,
  category: "Sports & Outdoors",
  title: "Camping Tent 4-Person",
  price: 129.00,
  oldPrice: 149.00,
  image: "/images/Sports & Outdoors/Camping Tent 4-Person.jpg",
  description: "Spacious 4-person tent with weather-resistant fabric and quick setup system. Ideal for camping and outdoor trips.",
  sold: 77,
  rating: 4.8,
  quntity: 12,
  about: "Enjoy your outdoor adventures with this easy-to-assemble camping tent. It provides excellent ventilation, waterproof protection, and enough space for the whole family. Perfect for weekend getaways or hiking trips.",
  size: "large",
  color: ["Green", "Gray"],
},

// 🧸 Toys & Games
{
  id: 501,
  category: "Toys & Games",
  title: "Building Blocks Set 120pcs",
  price: 29.00,
  oldPrice: 39.00,
  image: "/images/Toys & Games/Building Blocks Set 120pcs.jpg",
  description: "Colorful building block set that encourages creativity and motor skills in kids. Safe, durable, and easy to clean.",
  sold: 216,
  rating: 4.9,
  quntity: 30,
  about: "Spark imagination and creativity with this large building block set. Designed for safety and fun, it helps children develop problem-solving and coordination skills through play.",
  size: "large",
  color: ["Multicolor"],
},
{
  id: 502,
  category: "Toys & Games",
  title: "Remote Control Car Turbo X",
  price: 45.00,
  oldPrice: 59.00,
  image: "/images/Toys & Games/Remote Control Car Turbo X.jpg",
  description: "High-speed remote control car with rechargeable battery and durable frame. Perfect for indoor and outdoor racing.",
  sold: 178,
  rating: 4.7,
  quntity: 18,
  about: "Race into excitement with the Turbo X RC Car. Featuring fast acceleration, responsive controls, and tough design, it delivers endless fun for both kids and adults.",
  size: "medium",
  color: ["Red", "Blue"],
},
{
  id: 503,
  category: "Toys & Games",
  title: "Educational Puzzle Set",
  price: 19.99,
  oldPrice: 25.00,
  image: "/images/Toys & Games/Educational Puzzle Set.webp",
  description: "Colorful educational puzzle designed to develop logic and learning skills in young children. Safe and eco-friendly material.",
  sold: 153,
  rating: 4.8,
  quntity: 25,
  about: "Make learning fun with this interactive puzzle set. Encourages cognitive growth and problem-solving in a playful way, perfect for preschoolers and early learners.",
  size: "medium",
  color: ["Multicolor"],
},
{
  id: 504,
  category: "Toys & Games",
  title: "Plush Teddy Bear 60cm",
  price: 35.00,
  oldPrice: 49.00,
  image: "/images/Toys & Games/Plush Teddy Bear 60cm.webp",
  description: "Soft and cuddly teddy bear made with premium plush material. A perfect gift for kids or loved ones.",
  sold: 201,
  rating: 4.9,
  quntity: 15,
  about: "Bring smiles and warmth with this adorable plush teddy bear. Its ultra-soft fur and huggable size make it a comforting companion for kids and collectors alike.",
  size: "large",
  color: ["Brown", "Cream"],
},
{
  id: 505,
  category: "Toys & Games",
  title: "Kids Drawing Kit Deluxe",
  price: 28.00,
  oldPrice: 35.00,
  image: "/images/Toys & Games/Kids Drawing Kit Deluxe.avif",
  description: "Complete art kit with crayons, markers, and sketchbook. Encourages creativity and fine motor development.",
  sold: 145,
  rating: 4.7,
  quntity: 22,
  about: "Unleash your child's artistic talent with this all-in-one drawing kit. Includes high-quality tools designed for safe, endless creativity and fun.",
  size: "medium",
  color: ["Multicolor"],
},

// 📚 Books & Stationery
{
  id: 601,
  category: "Books & Stationery",
  title: "Classic Notebook A5",
  price: 9.99,
  oldPrice: 15.00,
  image: "/images/Books & Stationery/Classic Notebook A5.jpg",
  description: "Premium ruled notebook with thick pages and leather cover. Ideal for journaling, note-taking, or planning.",
  sold: 310,
  rating: 4.9,
  quntity: 50,
  about: "Keep your thoughts and ideas organized with this elegant A5 notebook. Crafted with durable cover and smooth pages for a pleasant writing experience, perfect for students and professionals.",
  size: "small",
  color: ["Black", "Brown"],
},
{
  id: 602,
  category: "Books & Stationery",
  title: "Gel Pen Set (12 Colors)",
  price: 12.00,
  oldPrice: 18.00,
  image: "/images/Books & Stationery/Gel Pen Set (12 Colors).webp",
  description: "Smooth-writing gel pens in 12 vibrant colors. Quick-drying ink ideal for school, art, or office work.",
  sold: 184,
  rating: 4.8,
  quntity: 40,
  about: "Add color to your notes with these smooth-flowing gel pens. Designed for precision and comfort, the pens feature fade-resistant ink perfect for creative projects and daily use.",
  size: "small",
  color: ["Multicolor"],
},
{
  id: 603,
  category: "Books & Stationery",
  title: "Desk Organizer Set",
  price: 29.00,
  oldPrice: 35.00,
  image: "/images/Books & Stationery/Desk Organizer Set.avif",
  description: "Stylish desk organizer set with multiple compartments. Keeps your workspace tidy and efficient.",
  sold: 123,
  rating: 4.7,
  quntity: 18,
  about: "Keep your desk clutter-free with this modern organizer set. Crafted from durable materials, it’s perfect for storing pens, papers, and accessories in style.",
  size: "medium",
  color: ["Black", "Gray"],
},
{
  id: 604,
  category: "Books & Stationery",
  title: "Inspirational Quote Journal",
  price: 14.99,
  oldPrice: 20.00,
  image: "/images/Books & Stationery/Inspirational Quote Journal.webp",
  description: "Motivational journal with 200 lined pages and inspiring quotes. Great for reflection and daily writing.",
  sold: 167,
  rating: 4.9,
  quntity: 25,
  about: "Start every day inspired with this motivational journal. Each page features an uplifting quote to keep you focused and positive as you write your thoughts and goals.",
  size: "small",
  color: ["White", "Gold"],
},
{
  id: 605,
  category: "Books & Stationery",
  title: "Study Lamp Foldable LED",
  price: 22.00,
  oldPrice: 30.00,
  image: "/images/Books & Stationery/Study Lamp Foldable LED.jpg",
  description: "Foldable LED lamp with adjustable brightness and USB charging. Perfect for study or work desks.",
  sold: 99,
  rating: 4.6,
  quntity: 20,
  about: "Illuminate your study space with this compact and efficient LED lamp. It features adjustable angles, soft light, and energy-saving design for long hours of reading or work.",
  size: "medium",
  color: ["White", "Silver"],
},

// 🪑 Furniture
{
  id: 701,
  category: "Furniture",
  title: "Modern Office Chair",
  price: 129.00,
  oldPrice: 159.00,
  image: "/images/Furniture/Modern Office Chair.avif",
  description: "Ergonomic office chair with lumbar support and adjustable height. Breathable mesh for all-day comfort.",
  sold: 87,
  rating: 4.7,
  quntity: 10,
  about: "Work in comfort with this modern office chair designed to support your posture. Its ergonomic features help reduce strain and enhance productivity, making it ideal for long working hours.",
  size: "large",
  color: ["Black", "Gray"],
},
{
  id: 702,
  category: "Furniture",
  title: "Wooden Coffee Table",
  price: 99.00,
  oldPrice: 120.00,
  image: "/images/Furniture/Wooden Coffee Table.jpeg",
  description: "Elegant wooden coffee table with smooth finish and sturdy legs. Perfect centerpiece for your living room.",
  sold: 65,
  rating: 4.6,
  quntity: 8,
  about: "Add warmth and elegance to your home with this handcrafted wooden coffee table. Built from premium wood with a natural finish that complements any modern or classic décor.",
  size: "large",
  color: ["Brown", "Walnut"],
},
{
  id: 703,
  category: "Furniture",
  title: "Minimalist Bookshelf 5-Tier",
  price: 139.00,
  oldPrice: 165.00,
  image: "/images/Furniture/Minimalist Bookshelf 5-Tier.webp",
  description: "5-tier bookshelf made from solid wood with a modern minimalist design. Great for books or decorative items.",
  sold: 48,
  rating: 4.8,
  quntity: 6,
  about: "Display your books and treasures in style with this minimalist 5-tier bookshelf. Sturdy, elegant, and space-efficient — perfect for living rooms, offices, or bedrooms.",
  size: "large",
  color: ["Oak", "White"],
},
{
  id: 704,
  category: "Furniture",
  title: "Queen Size Bed Frame",
  price: 299.00,
  oldPrice: 349.00,
  image: "/images/Furniture/Queen Size Bed Frame.avif",
  description: "Sturdy queen size bed frame with upholstered headboard and solid wooden slats. Easy to assemble and durable.",
  sold: 52,
  rating: 4.7,
  quntity: 5,
  about: "Upgrade your bedroom comfort with this modern queen bed frame. Designed for durability and luxury, it combines strong materials with an elegant aesthetic.",
  size: "large",
  color: ["Gray", "Beige"],
},
{
  id: 705,
  category: "Furniture",
  title: "Dining Chair Set (4 pcs)",
  price: 249.00,
  oldPrice: 279.00,
  image: "/images/Furniture/Dining Chair Set (4 pcs).jpeg",
  description: "Set of four dining chairs with cushioned seats and ergonomic backrest. Built for comfort and modern aesthetics.",
  sold: 73,
  rating: 4.8,
  quntity: 7,
  about: "Dine in style and comfort with this premium 4-piece chair set. The modern design blends beautifully with any interior, offering both durability and luxurious seating experience.",
  size: "large",
  color: ["Beige", "Black"],
},


];

export default products;
